project_id = "dvnapflludhnncmuakla"

[functions.send-contact-email]
verify_jwt = false

[functions.create-calendar-event]
verify_jwt = false

[functions.check-calendar-availability]
verify_jwt = false